title: Filippo Pota
logo: 
description: I am a PhD candidate in Chemistry with a passion for research and a growing interest in data science and analytics.
show downloads: true
theme: jekyll-theme-minimal
